In [ ]:
!pip install faker

Collecting faker
  Downloading Faker-33.1.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from faker) (4.12.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.17.0)
Downloading Faker-33.1.0-py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 19.5 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-33.1.0

In [ ]:
import pandas as pd
import random
from faker import Faker
from datetime import date
import calendar

In [ ]:
#fake = Faker()

carburants = ["Essence", "Diesel", "Electrique", "Hybride"]
boites_vitesse = ["Manuelle", "Automatique"]
types_vehicules = ["Berline", "Break", "SUV", "Coupé", "Monospace", "Pick-up"]
pays_origine = ["France", "Allemagne", "Suede", "Italie", "Espagne", "Belgique", "Royaume-Uni", "Autriche"]
couleurs = ["Noir", "Blanc", "Gris", "Bleu", "Rouge", "Vert", "Jaune", "Argent", "Orange"]
critaires_air = ["Euro 4", "Euro 5", "Euro 6", "Euro 6", "Euro 7", "Euro 8"]
classes_co2 = ["A", "B", "C", "D", "E"]
types_puissance = ["65", "75", "90", "95", "110", "120", "130", "150", "200"]


# Dictionnaire des marques et de leurs modèles
marques_modeles = {
    "Renault": ["Clio", "Megane", "Talisman", "Captur"],
    "Peugeot": ["208", "3008", "5008", "308"],
    "BMW": ["Serie 1", "Serie 3", "GTR", "X5"],
    "Audi": ["A3", "A4", "Q5", "A6"],
    "Mercedes": ["Classe A", "Classe C", "Classe E", "GLC"],
    "Volkswagen": ["Golf", "Passat", "Tiguan", "Arteon"],
    "Toyota": ["Yaris", "Corolla", "Hilux", "RAV4"]
}

# Dictionnaire des prix de base par marque et modèle
prix_de_base = {
    "Renault": {"Clio": 49000, "Megane": 58000, "Talisman": 45000, "Captur": 45000},
    "Peugeot": {"208": 36000, "3008": 55000, "5008": 57000, "308": 39000},
    "BMW": {"Serie 1": 45000, "Serie 3": 45000, "GTR": 65000, "X5": 60000},
    "Audi": {"A3": 28000, "A4": 35000, "Q5": 63000, "A6": 55000},
    "Mercedes": {"Classe A": 39000, "Classe C": 45000, "Classe E": 55000, "GLC": 60000},
    "Volkswagen": {"Golf": 49000, "Passat": 37000, "Tiguan": 45000, "Arteon": 45000},
    "Toyota": {"Yaris": 46000, "Corolla": 55000, "Hilux": 49000, "RAV4": 50000}
}
# Fonction pour calculer le prix de la voiture en fonction de la marque et du modèle
def calculer_prix(annee_modele, km, marque, modele):
    # Vérifier si la marque et le modèle sont dans le dictionnaire
    if marque not in prix_de_base or modele not in prix_de_base[marque]:
        print(f"Marque ou modèle inconnu : {marque} {modele}")
        return None

    prix_initial = prix_de_base[marque][modele]  # Valeur de base par marque et modèle
    # Calcul de la perte annuelle de valeur (environ 7% par an)
    age_voiture = 2024 - annee_modele
    perte_annuelle = prix_initial * 0.07 * age_voiture
    # Calcul de la perte en fonction des kilomètres (1% par tranche de 10 000 km)
    perte_km = (km // 10000) * 0.01 * prix_initial
    # Calcul du prix final
    prix_final = prix_initial - perte_annuelle - perte_km
    # Retourner le prix final avec un prix minimum de 1000€
    return max(prix_final, 1000)  # Le prix ne doit pas descendre en dessous de 1000€

# Exemple d'utilisation
#prix_voiture = calculer_prix(2018, 60000, "Peugeot", "3008")
#print(f"Prix estimé de la voiture : {prix_voiture}€")

# Nombre de voitures à générer
n_voitures = 7000

# Générer les données
data = []
for _ in range(n_voitures):
    marque = random.choice(list(marques_modeles.keys()))
    modele = random.choice(marques_modeles[marque])
    annee_modele = random.randint(2005, 2024)
    km = random.randint(10000, 250000)

    # L'année de mise en circulation : 1-3 ans après l'année du modèle
    annee_mise_en_circulation = random.randint(annee_modele, annee_modele + 3)
    # Générer un mois et un jour aléatoires en fonction de l'année de mise en circulation
    mois = random.randint(1, 12)
    jour = random.randint(1, calendar.monthrange(annee_mise_en_circulation, mois)[1])
    # Formatage du mois et du jour pour avoir des valeurs à 2 chiffres
    mois = str(mois).zfill(2)  # Ajouter un zéro devant si le mois est inférieur à 10
    jour = str(jour).zfill(2)
    # Créer la date de mise en circulation
    #date_mise_en_circulation = date(annee_mise_en_circulation, mois, jour)
    date_mise_en_circulation = f"{annee_mise_en_circulation}-{mois}-{jour}"

    carburant = random.choice(carburants)
    boite_vitesse = random.choice(boites_vitesse)
    puissance = random.choice(types_puissance)
    critere_air = random.choice(critaires_air)
    classe_co2 = random.choice(classes_co2)
    couleur = random.choice(couleurs)
    type_vehicule = random.choice(types_vehicules)
    pays = random.choice(pays_origine)
    # Calculer le prix de la voiture
    prix = calculer_prix(annee_modele, km, marque, modele)

    # Ajouter toutes les données dans la liste
    data.append({
        "Marque": marque,
        "Modele": modele,
        "Annee modele": annee_modele,
        "Km": km,
        "Date de premiere mise en circulation": date_mise_en_circulation,
        "Carburant": carburant,
        "Boite de vitesse": boite_vitesse,
        "Puissance": puissance,
        "Critere air": critere_air,
        "Classe emission CO2": classe_co2,
        "Couleur": couleur,
        "Type de vehicule": type_vehicule,
        "Pays": pays,
        "Prix": prix
    })
# Créer le DataFrame
df = pd.DataFrame(data)

# Afficher les premières lignes du dataset
print(df.head())

# Sauvegarder le dataset en fichier CSV
df.to_csv("dataset_voitures_avec_prix.csv", index=False)

# Si tu veux sauvegarder en Excel, tu peux utiliser cette ligne :
# df.to_excel("dataset_voitures_avec_prix.xlsx", index=False)

     Marque    Modele  Annee modele      Km  \
0   Peugeot       208          2016  190748
1    Toyota      RAV4          2011   90709
2   Renault  Talisman          2006  212685
3  Mercedes  Classe E          2014   70045
4      Audi        A4          2007  202052

  Date de premiere mise en circulation   Carburant Boite de vitesse Puissance  \
0                           2016-05-29      Diesel         Manuelle       120
1                           2011-09-28  Électrique      Automatique        65
2                           2007-03-21  Électrique      Automatique       150
3                           2014-06-28     Hybride         Manuelle        65
4                           2010-01-06     Essence      Automatique        75

  Critere air Classe emission CO2 Couleur Type de vehicule         Pays  \
0      Euro 7                   A   Blanc        Monospace  Royaume-Uni
1      Euro 6                   C   Rouge          Pick-up      Espagne
2     Euro 6d                   B   Blanc              SUV   États-Unis
3      Euro 7                   C    Bleu          Pick-up      Espagne
4      Euro 7                   A   Rouge          Berline       France

      Prix
0   9000.0
1   1000.0
2   1000.0
3  12650.0
4   1000.0

In [4]:
import pandas as pd
import random
#from faker import Faker
from datetime import date
import calendar

# Initialiser Faker
#fake = Faker()

# Prix réels initiaux pour chaque marque et modèle
prix_neufs = {
    "Renault": {"Clio": 17000, "Megane": 25000, "Talisman": 40000, "Captur": 28000},
    "Peugeot": {"208": 18000, "3008": 35000, "5008": 42000, "308": 30000},
    "BMW": {"Serie 1": 35000, "Serie 3": 45000, "Serie 5": 65000, "X5": 80000},
    "Audi": {"A3": 34000, "A4": 48000, "Q5": 65000, "A6": 72000},
    "Mercedes": {"Classe A": 38000, "Classe C": 55000, "Classe E": 75000, "GLC": 85000},
    "Volkswagen": {"Golf": 25000, "Passat": 36000, "Tiguan": 40000, "Arteon": 48000},
    "Toyota": {"Yaris": 19000, "Corolla": 28000, "Hilux": 45000, "RAV4": 37000},
    "Citroen": {"C3": 16000, "C4": 24000, "C5 Aircross": 35000},
    "Ford": {"Fiesta": 18000, "Focus": 26000, "Kuga": 34000},
    "Tesla": {"Model 3": 45000, "Model S": 95000, "Model X": 120000},
    "Dacia": {"Sandero": 15900, "Duster": 19900, "Spring": 22000},
    "Hyundai": {"i20": 19500, "i30": 22000, "Tucson": 35000},
    "Kia": {"Rio": 18900, "Ceed": 23000, "Sportage": 34000},
}

# Listes d'autres variables
carburants = ["Essence", "Diesel", "Hybride", "Electrique", "Gaz"]
boites_vitesse = ["Manuelle", "Automatique"]
types_puissance = [90, 110, 130, 150, 200]
couleurs = ["Rouge", "Bleu", "Noir", "Blanc", "Gris"]
types_vehicules = ["Berline", "Crossover", "Break", "SUV", "Monospace"]
pays_origine = ["France", "Allemagne", "Espagne", "Italie", "Japon", "USA"]

# Fonction pour déterminer le critère d'air
def determiner_critere_air(annee_modele, carburant):
  if carburant in ["Electrique", "Hybride"]:
      return "Euro 1"
  elif carburant == "Diesel":
      age = 2024 - annee_modele
      return f"Euro {min(6, max(2, 6 - (age // 5)))}"
  else:
      age = 2024 - annee_modele
      return f"Euro {min(6, max(1, 6 - (age // 5)))}"

# Fonction pour calculer le prix d'occasion
def calculer_prix_occassion(prix_initial, annee_modele, km, carburant, boite_vitesse, puissance):
    # Ajustements selon les caractéristiques
    if boite_vitesse == "Automatique":
        prix_initial += 2000
    if carburant == "Essence":
        prix_initial -= 1000
    elif carburant == "Electrique":
        prix_initial += 5000
    elif carburant == "Hybride":
        prix_initial += 3000
    elif carburant == "Gaz":
        prix_initial += 1500
    prix_initial += puissance * 10  # Ajustement par puissance

    # Dépréciation selon l'âge et le kilométrage
    age_voiture = 2024 - annee_modele
    perte_annuelle = prix_initial * 0.03 * age_voiture
    perte_km = (km // 10000) * 0.01 * prix_initial
    prix_final = prix_initial - perte_annuelle - perte_km
    return max(prix_final, 1000)  # Prix minimum de 1000€

# Nombre de voitures à générer
n_voitures = 7000

# Générer les données
data = []
for _ in range(n_voitures):
    marque = random.choice(list(prix_neufs.keys()))
    modele = random.choice(list(prix_neufs[marque].keys()))
    prix_neuf = prix_neufs[marque][modele]

    annee_modele = random.randint(2005, 2024)
    carburants_disponibles = [c for c in carburants if not (c == "Electrique" and annee_modele < 2018)]
    carburants_disponibles = [c for c in carburants_disponibles if not (c == "Hybride" and annee_modele < 2010)]
    carburant = random.choice(carburants_disponibles)

    annee_mise_en_circulation = random.randint(annee_modele, annee_modele + 3)
    mois = str(random.randint(1, 12)).zfill(2)
    jour = str(random.randint(1, calendar.monthrange(annee_mise_en_circulation, int(mois))[1])).zfill(2)
    date_mise_en_circulation = f"{annee_mise_en_circulation}-{mois}-{jour}"

    km = random.randint(10000, 250000)
    boite_vitesse = random.choice(boites_vitesse)
    puissance = random.choice(types_puissance)
    critere_air = determiner_critere_air(annee_modele, carburant)
    couleur = random.choice(couleurs)
    type_vehicule = random.choice(types_vehicules)
    pays = random.choice(pays_origine)

    # Calculer le prix d'occasion
    prix_occassion = calculer_prix_occassion(prix_neuf, annee_modele, km, carburant, boite_vitesse, puissance)

    # Ajouter les données
    data.append({
        "Marque": marque,
        "Modele": modele,
        "Annee_modele": annee_modele,
        "Km": km,
        "Date_premiere_mise_en_circulation": date_mise_en_circulation,
        "Carburant": carburant,
        "Boite_vitesse": boite_vitesse,
        "Puissance": puissance,
        "Critere_air": critere_air,
        "Couleur": couleur,
        "Type_vehicule": type_vehicule,
        "Pays": pays,
        "Prix_neuf": prix_neuf,
        "Prix_occassion": prix_occassion
    })

# Créer le DataFrame
df = pd.DataFrame(data)

# Afficher les premières lignes du dataset
print(df.head())

# Sauvegarder le dataset en fichier CSV
df.to_csv("dataset_Car.csv", index=False)

    Marque       Modele  Annee_modele      Km  \
0     Audi           Q5          2024   53285
1    Tesla      Model X          2014  136632
2    Tesla      Model X          2016   90147
3  Citroen  C5 Aircross          2013  101009
4   Toyota        Yaris          2018  173267

  Date_premiere_mise_en_circulation Carburant Boite_vitesse  Puissance  \
0                        2026-09-18   Essence   Automatique        110
1                        2017-02-01    Diesel   Automatique        110
2                        2019-04-02   Hybride      Manuelle        110
3                        2014-03-18       Gaz      Manuelle        200
4                        2021-04-17    Diesel   Automatique        110

  Critere_air Couleur Type_vehicule     Pays  Prix_neuf  Prix_occassion
0      Euro 6    Bleu     Monospace  Espagne      65000         63745.0
1      Euro 4    Bleu         Break      USA     120000         70167.0
2      Euro 1    Gris     Crossover    Japon     120000         83147.0
3      Euro 4    Gris     Crossover  Espagne      35000         21945.0
4      Euro 5   Blanc       Berline   Italie      19000         14365.0